# Exported from Render on 2025-11-26T07:44:34Z

  
  	services:
    - type: web
      name: projectSem42025
      runtime: docker
      plan: free
      buildCommand: docker build -t projectSem42025 .
      startCommand: docker run -p 8989:8989 projectSem42025
      envVars:
        - key: SERVER_PORT
          value: 8989
      region: oregon
      autoDeployTrigger: commit