services:
  - type: web
    name: OmniShop
    runtime: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 21
      - key: SERVER_PORT
        value: 8989